### ISSUE TITLE
Add Image to extension

### ISSUE THREAD

**Issue by all360** [openfl/extension-share#10]
For Android I would like to share an image and text. I was able to get this to work for IOS but now I am having an issue with Android.

How can I modify the ShareEx.java file so I can post an image and text?

Thanks

**Comment by fbricker** [comment]
Hi, I've not tried to share images on Android yet, but I guess it shouldn't be complicated to implement. I'll take a look at this when I got some time. Meanwhile, if you figure out how to do it, please tell us here or send a pull request to the extension so we can add it faster :)

Thanks!

**Comment by hcwdikk** [comment]
Hey, this share extension is great, it helped me quite a lot :)
I've managed to share an image thanks to your code, it looks like this on ios:
http://pastebin.com/dzgjRAfp
First I'm saving an image somewhere in external directory so other apps (such as facebook) have access to it. Then I pass the path to this image to my extension.

I'll post android code later when I get back home, I hope it helps somehow :D

**Comment by hcwdikk** [comment]
http://pastebin.com/VS122dt1

android code

**Comment by fbricker** [comment]
Hi hcwdikk, that's is great!
Do you mind making a Pull request here on github so that we can accept this directly and make it official?

Thanks!

**Comment by hcwdikk** [comment]
sure, I think I'll have some spare time on friday or saturday to do that :)

**Comment by fbricker** [comment]
Great!!!! Thanks in advance :+1:

**Comment by fierysquirrel** [comment]
If there is anything I can do to help adding the image functionality please let me know, that feature sounds very useful!

**Comment by hcwdikk** [comment]
I'm really sorry, I completly forgot about this :(
I've just created pull request for android image sharing.

**Comment by hcwdikk** [comment]
ios is also done

**Comment by fierysquirrel** [comment]
That's awesome! thank you very much, really appreciate it, I'm going to try it soon, cheers!

**Comment by fbricker** [comment]
Hi, can someone confirm if this pull request https://github.com/openfl/extension-share/pull/16 is working fine?
If so, I can merge it and upgrade the extension on haxelib.

**Comment by fbricker** [comment]
Done! I've merged the PR and upgraded the extension on haxelib.

Thanks! 👍
