### ISSUE TITLE
Callback with sharing info

### ISSUE THREAD

**Issue by Netforza** [openfl/extension-share#11]
Does the "extention-share" allow to know if a user has shared the app, and which platform it chose for sharing?
Thank you

**Comment by fbricker** [comment]
Hi, no. The extension does not keep track on the user shares, so it can't tell you if the user has shared the app.

About the platform used, generally we use this extension to share some URL that will work on most platforms (like http://www.sempaigames.com/daktylos/ or http://www.puralax.com/mobile/). This way, if a user from iPhone shares the URL, his friends from Android will be able to use the link.

But, if you want to make android users to share the Android Link, and iPhone users to share iPhone links, you should implement that yourself by adding #if android /// #if ios /// lines.

Thanks!
