### ISSUE TITLE
issue with -Dnext compilation flag

### ISSUE THREAD

**Issue by ramsestom** [openfl/extension-share#14]
Hi.

   I am having this issue when compiling with -Dnext (openfl 3.3.3):

 [javac] Compiling 8 source files to C:\Development\haxe\Darkaedalus\export\android\bin\bin\classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] C:\Development\haxe\Darkaedalus\export\android\bin\src\shareex\ShareEx.java:16: error: cannot find symbol
    [javac]         GameActivity.getInstance().getContext().startActivity(sendIntent);
    [javac]                     ^
    [javac]   symbol:   method getInstance()
    [javac]   location: class GameActivity
    [javac] Note: C:\Development\haxe\Darkaedalus\export\android\bin\src\org\libsdl\app\SDLActivity.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error
    [javac] 3 warnings

works fine when compiled with openfl legacy though.

**Comment by jgranick** [comment]
Would the extension work if we used `org.haxe.extension.Extension.mainActivity` instead of trying to reference `GameActivity`? The structure (or existence) of "GameActivity" is not guaranteed :smile:

**Comment by fbricker** [comment]
Hi, I think we could change that... I'll try it now and let you know :)

**Comment by fbricker** [comment]
Done! In addition to that, I had to add one flag to the intent:
```haxe
sendIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
```
And it's working on both (next and legacy) :+1: 

Already pushed to github and haxelib.

Thanks for reporting!

**Comment by jgranick** [comment]
Awesome, thanks! :smile:

**Comment by ramsestom** [comment]
Perfect. Thanks! :+1:

**Comment by KienSama** [comment]
i want to know when user share success or fail, can you help me?
