### ISSUE TITLE
Can't build for flash

### ISSUE THREAD

**Issue by pozirk** [openfl/extension-share#17]
Hello!
Can't build my project with the latest 2.4.1. share extension for flash target, didn't try other targets.
Get the following:
`C:/HaxeToolkit/haxe/lib/extension-share/2,4,1/extension/share/Share.hx:5: characters 7-18 : You cannot access the sys package while targeting flash (for sys.io.File)`
Same for
`import sys.FileSystem;`

Had no problems with 2.2.1.

Here is the commit, that's responsible for the problem:
https://github.com/openfl/extension-share/commit/a5d24c8af1a39e89dae5824ef9df688440cddc3f#diff-150d1cfc3e34cecaafb8d397ae0b2c50

Any help?
Thank you!

**Comment by fbricker** [comment]
Hi, thanks for reporting. I've fixed this and pushed a new release to haxelib.
