### ISSUE TITLE
iOS 7 crash

### ISSUE THREAD

**Issue by Waynetron** [openfl/extension-share#2]
Calling Share.share on iOS 7 causes a crash.

**Comment by kitchsGithubName** [comment]
I can confirm this, perhaps with a little more elaboration.  Seeing the same thing (iPhone - iOS 7.1.1)

My initial call was significantly more complex, however I was able to duplicate it with this:

Share.init(Share.TWITTER);
Share.share("IM ON THE TWITTERZ!");

Xcode gives me the following:
![screen shot 2015-02-24 at 12 05 42 am](https://cloud.githubusercontent.com/assets/10752411/6344108/3eb514b0-bbb9-11e4-93bc-7c99faa68581.png)

Also, on a side note, on an iPad ( iOS 8.1.2)  The same call give me :
![screen shot 2015-02-24 at 12 13 19 am](https://cloud.githubusercontent.com/assets/10752411/6344184/ccae974a-bbba-11e4-949c-8e829286da8c.png)

It does not crash, but gives the generic "What do you want to share to" dialog, including twitter/message/email, etc.  Supplying a defaultURL and defaultSubject, that just shows the "invalidationHandler calle" message, without all the other stuff... Plus the generic dialog.

**Comment by kitchsGithubName** [comment]
Finally got some time to look into this again.  I wrapped all the new iPad code in an if statement, and it now appears to work for me on iOS 7 on an iPhone, and iOS 8 on an iPad.  

But an objective-c programmer I am not...  I am an objective-c hack... so I'll throw that disclaimer in there.

if ( UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad )
{
	// Required for iPad
	activityVC.popoverPresentationController.sourceView = [[UIApplication sharedApplication] keyWindow];

	// Remove arrow from action sheet.
	[activityVC.popoverPresentationController setPermittedArrowDirections:0];

	// Set action sheet to middle of view.
	activityVC.popoverPresentationController.sourceRect = [[UIApplication sharedApplication] keyWindow].frame;
	
}

Thank you for the extension!

**Comment by pozirk** [comment]
Just caught the same exception on iOS 7, had no such problems with iOS 8.
Would be good to update the extension.

**Comment by fbricker** [comment]
Hi, this has been just solved with version 1.2.2 of the extension. Sorry for being disconnected so long.

By the way, you should install and use "extension-share" now (the old openfl-share is now deprecated).

**Comment by pozirk** [comment]
Nice, thank you!
